---
- name: add repo
  template:
    src: nginx.repo
    dest: /etc/yum.repos.d/nginx.repo

- name: install nginx
  yum: name=nginx state=present enablerepo=nginx

- name: start nginx
  service: name=nginx state=started enabled=yes
