---
- name: remove mariadb-libs
  yum: name=mariadb-libs state=absent

- name: remove mariadb lib directory
  shell: sudo rm -rf /var/lib/mysql

- name: remove mysql
  yum: name=mysql* state=absent

- name: add repo
  yum: name=http://dev.mysql.com/get/mysql57-community-release-el7-11.noarch.rpm state=present

- name: install mysql
  yum: name=mysql-community-server state=present

- name: start mysql
  service: name=mysqld state=started enabled=yes
